### ISSUE TITLE
Options for none Admin

### ISSUE THREAD

**Issue by beegegroup** [inspiredminds/contao-event-registration#10]
Hi, 
is it possible, that the Options are not available for non-Admins?

The User has the right to edit events and Forms... but doesn't see following options:
![Bildschirmfoto 2022-08-19 um 13 45 48](https://user-images.githubusercontent.com/109108988/185611709-8727db9c-3bfb-4ade-a140-21fd47ed2241.png)

Kind Regards

Stefan

**Comment by fritzmg** [comment]
For non-admins you need to specifically allow these `tl_calendar_events` fields in the back end user group settings.

**Comment by beegegroup** [comment]
hi,
my bad... seems to be working.
