### ISSUE TITLE
Contao 4.13.10 Registration confirmation not working

### ISSUE THREAD

**Issue by dive13** [inspiredminds/contao-event-registration#11]
The registration confirmation does not work under 4.13.10. I cannot receive the confirmation mail. Other mails via Notification Center work without problems.

I placed the module "event registration confirmation" on a separate page, but it is not even shown in the source code. 

I currently don't have kmielke/calendar-extended-bundle installed (had it for a short time, but because of other problems with the extension uninstalled again).

**Comment by fritzmg** [comment]
I cannot confirm the problem. The event registration (and also cancellation) notifications are sent, when a registered user uses their confirm or cancel link from the initial registration.

> I placed the module "event registration confirmation" on a separate page

Did you configure that page in the calendar's settings?

> but it is not even shown in the source code.

It will only show up when there is an `action` and `uuid` parameter in the URL.

**Comment by dive13** [comment]
Thanks for the quick response.

Hmm … looks like an operating error :) All the time I thought the event registration notification was responsible for the opt-in-process, so I integrated the ##reg_confirm_url## there.

It was not clear to me that this process requires a normal notification first (Contao form submission in the NC).

Now it works :)

Maybe this could be clarified in the Readme.
btw: [this instruction in the Contao Forum](https://community.contao.org/de/showthread.php?82553-Einrichtung-inspiredminds-contao-event-registration&highlight=event-registration) is also not very precise regarding this topic (Pt. 4)

**Comment by fritzmg** [comment]
> Maybe this could be clarified in the Readme.

Feel free to create a PR. Currently the following is mentioned in the README:

> The confirmation and cancellation forms can be inserted on other pages. In that case you also need to specify those pages in the settings of the calendar. Otherwise it is assumed that those modules are also present on the event reader page. The modules allow you to define a node for detailed content. This content will be displayed, when an event registration has been successfully confirmed or cancelled. You are also able to select a notification that will be sent after succesful cancellation or confirmation. If you do not need either confirmation or cancellation functionality, these modules do not need to be created.

\\

> btw: [this instruction in the Contao Forum](https://community.contao.org/de/showthread.php?82553-Einrichtung-inspiredminds-contao-event-registration&highlight=event-registration) is also not very precise regarding this topic (Pt. 4)

I have no influence over that, as this was done by a community member.

**Comment by BlackThunder22** [comment]
I have the same problem. Have you found a solution?

**Comment by dive13** [comment]
Yes, as I mentioned in my comment above.
