### ISSUE TITLE
Problem mit Benachrichtigungen

### ISSUE THREAD

**Issue by Cleanerrr** [inspiredminds/contao-event-registration#14]
Hallo,

ich habe alles wie beschrieben gemacht und fast alles funktioniert. Über die klassische Benachrichtigung kommt eine E-Mail mit einem Link zur Bestätigung der Registrierung, sowie eine weitere Benachrichtigung für den Admin, dass der neue Teilnehmer registriert (aber nicht bestätigt) ist. Ein Detail funktioniert bei mir nicht. Nachdem Sie auf den Link zur Bestätigung der Registrierung geklickt haben, passiert nichts. Ich habe erst dann E-Mails erwartet, eine für den Admin, dass die Registrierung bestätigt wurde, und eine für den Teilnehmer, dass er die Registrierung erfolgreich bestätigt hat.

Im zweiten Fall, wenn es nicht nötig ist, schalte ich die Verpflichtung zur Bestätigung der Anmeldung aus, und dann funktioniert alles, außer dass in Event-bekend der neue Teilnehmer nicht bestätigt wird, hier meine ich, die Symbole sind grau, nicht grün wie erwartet für einen registrierten Teilnehmer.

Sind das Fehler in den Einstellungen oder sind es fehlende Plugins?

Danke im Voraus

**Comment by fritzmg** [comment]
> Nachdem Sie auf den Link zur Bestätigung der Registrierung geklickt haben, passiert nichts.

Did you add the _Event registration confirmation_ module to the confirmation page configured in your calendar (if you configured one)?

**Comment by Cleanerrr** [comment]
Yes, I tried that too, but it still doesn't work

**Comment by fritzmg** [comment]
> Yes, I tried that too

That's what you _have_ to do, if you want to use this feature. Otherwise the confirmation link won't do anything.

**Comment by fritzmg** [comment]
> created a new subpage

If you use a _separate_ page for the confirmation link, then you have to configure that page in your calendar's settings. If you do not want to use a separate page - or do not configure a page, then the module needs to be inserted into the same page as the calendar's redirect page (i.e. where the event reader module is placed).

**Comment by Cleanerrr** [comment]
I read the configuration manual and did exactly that. I tried both variants, but none of them work for me.

**Comment by fritzmg** [comment]
> In general, an excellent plugin with a rather complicated configuration, whose instructions are very weak and unclearly written.

As this is an Open Source package, you are free to submit a PR to improve it.
