### ISSUE TITLE
PHP 8 - Probleme beim Versenden der Bestätigungs-Email

### ISSUE THREAD

**Issue by keved93** [inspiredminds/contao-event-registration#17]
Contao 4.13.*
PHP 8.0

Hi,
anscheinend ist das Modul noch nicht ganz PHP 8 fähig. Ich habe mich nach folgender Anleitung im Netz gehalten, die relativ "frisch" ist und scheinbar auch alles fast so funktioniert, wie es sein sollte. In den Events sind alle Registrierungen hinterlegt, Formulare werden mir angezeigt usw.

[Einrichtung inspiredminds/contao-event-registration](https://community.contao.org/de/showthread.php?82553-Einrichtung-inspiredminds-contao-event-registration)

Allerdings erhalte ich keine Bestätigungsemail, obwohl alles richtig konfiguriert sein sollte. Im Code selbst haben wir einen Fehler entdeckt, der bei PHP 8 einen Fehler (nur im Debug-Modus) zeigt: 

`(int) $submittedData['amount'] ?: 1; ->` 
[Link zur Zeile](https://github.com/inspiredminds/contao-event-registration/blob/395a465b9525ffd92a9e68bad4a5c8798ecbcc62/src/EventListener/EventRegistrationFormListener.php#L62C33-L62C69)

In PHP 8 wird erwartet, dass das Feld $submittedData['amount'] bereits existiert, ohne die restliche Prüfung, die in PHP 7 so noch funktioniert hat. Wir gehen davon aus, das noch weitere PHP 8 Probleme bestehen, der das Versenden der Bestätigungsmail verhindert.

**Comment by fritzmg** [comment]
Try

```php
$registration->amount = (int) ($submittedData['amount'] ?? null) ?: 1;
```

But that's likely not the reason why you did not receive an email (otherwise you would have seen an error). The error likely only occurs in debug mode.

**Comment by keved93** [comment]
Wir können dieses Problem mit einen einfachen Hidden-Feld lösen, das ist nicht das wirkliche Problem. Es deutet nur darauf hin, dass dieses Bundle noch nicht komplett auf PHP 8 umgestellt wurde. Das Problem ist der Versand der Bestätigungs-Email.

Wir haben selbst bei einer komplett cleanen Installation Probleme mit dem Versand der Bestätigungs-Email - auch unter der selben Anleitung wie im Beitrag des Forum. Wir haben den Notification-Center dann selbst noch einmal getestet, können den Fehler hier jedoch ausschließen, da wir die E-Mails von diesem Modul erhalten.

Alternativ könntest du uns ja einmal selbst unter der Anleitung ein Test mit PHP 8.0 und Contao 4.13.* machen, eventuell wurde hier ja etwas übersehen.

**Comment by fritzmg** [comment]
Ich kann leider kein Problem feststellen. Vielleicht gibt es auch einfach ein Missverständnis darüber, was genau mit "Bestätigungsemail" gemeint ist und habt daher vielleicht einfach nicht die richtigen Benachrichtigungen angelegt und eingestellt?

**Comment by keved93** [comment]
Ich glaube, ich habe den Fehler gefunden, bin mir allerdings unsicher. Dieses Modul einzubinden ist schon etwas komplex, wenn man das Modul überhaupt nicht kennt.

Wenn ich das jetzt richtig verstanden habe, aber auch leicht verwirrt:
Im Foren-Thread selbst ist der 4. Punkt mit dem Hinweis zu ##reg_confirm_url## falsch. Im Thread wird nicht erwähnt, dass eine ganz normale Formularübertragung über das Formular selbst stattfinden muss, um den Link von ##reg_confirm_url## zu erhalten. Ich habe damit eine E-Mail mit der URL erhalten.

Allerdings erhalte ich nach dem Aufruf des Links der normalen Formularübertragung auf die Bestätigungsseite erneut eine E-Mail mit dem Code, was von der "Event Registrierung: Registrierung bestätigen" stammt.

Wo genau soll das Modul hinterlegt werden, der sich um den Versand der "Registrierung bestätigen" Notifcation mit dem Link kümmert?

**Comment by fritzmg** [comment]
> Wo genau soll das Modul hinterlegt werden, der sich um den Versand der "Registrierung bestätigen" Notifcation mit dem Link kümmert? 

Dafür gibt es kein Modul. Die Extension erlaubt dir reguläre Contao Formulare zu benutzen - und daher können auch die regulären (vom Notification Center zur Verfügung gestellten) Formular-Benachrichtigungen dafür benutzt werden.

**Comment by keved93** [comment]
Dann liege ich also mit meiner Vermutung doch richtig, dass im Foren-Thread die Anleitung unvollständig bzw. ein wenig falsch ist. Besonders der 4. Punkt mit Hinweis zu ##reg_confirm_url## macht dann überhaupt keinen Sinn mehr, da hier explizit erwähnt wird, dass man sich hier im "Registrierung bestätigen" - Email befindet. "Registrierung bestätigen" als Wording wäre aber auch hier falsch, richtig wäre "Registierung bestätigt" - noch besser wäre "Bestätigungsmail nach erfolgreicher Registrierung". Man erwartet bei "Registrierung bestätigen" als Benutzer eine Aktion, den man selbst ausführen muss - hier erhält man allerdings dann nur noch eine E-Mail, dass die Registrierung abgeschlossen ist.

**Comment by fritzmg** [comment]
Der Forum Thread kommt nicht von mir. Du kannst dort ja eine berichtigung posten.
