### ISSUE TITLE
Contao 5.1

### ISSUE THREAD

**Issue by sdahlmann** [inspiredminds/contao-event-registration#18]
Question: Does the "inspiredminds/contao-event-registration" extension work with Contao 5.1? According to the description in the Contao Manager yes, but when installing via the Contao Manager I get an error message. Is that possibly because the "terminal42/notification_center" is not yet compatible with Contao 5.x? Is a Contao 5.1 fix of the extension planned?
![Contao_5 1](https://github.com/inspiredminds/contao-event-registration/assets/17680074/6eb5a787-482f-4e2f-9f58-420ce865b2dd)
> Resolving dependencies using Composer Cloud v3.6.0-1-g9d9036c
[7.5MiB/0.19s] Loading composer repositories with package information
[71.3MiB/8.50s] Updating dependencies
[105.0MiB/10.11s] Your requirements could not be resolved to an installable set of packages.
[105.0MiB/10.11s] 
  Problem 1
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.40.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.39.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.38.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.37.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.36.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.35.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.34.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.33.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.32.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.31.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.30.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.29.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.28.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.27.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.26.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.25.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.24.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.23.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.22.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.21.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.20.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.19.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.18.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.17.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.16.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.15.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.14.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.13.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.12.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.11.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.10.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.9.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.8.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.7.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.6.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.5.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.4.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.3.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.2.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.1.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.5.0.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.4.5.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.4.4.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.4.3.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.4.2.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.4.1.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.4.0.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.3.7.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.3.6.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.3.5.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.3.4.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.3.3.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.3.2.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.3.1.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.3.0.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.21.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.20.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.19.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.18.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.17.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.16.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.15.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.14.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.13.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.12.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.11.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.10.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.9.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.8.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.7.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.6.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.5.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.4.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.3.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.2.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.1.
    - con4gis/pwa v2.5.7 conflicts with contao/core 3.2.0.
    - inspiredminds/contao-event-registration[1.2.0, ..., 1.2.1] require contao/core-bundle ^4.9 -> found contao/core-bundle[4.9.0, ..., 4.13.28] but these were not loaded, likely because it conflicts with another require.
    - terminal42/notification_center[1.6.5, ..., 1.6.14] require contao/core-bundle ~4.4 -> found contao/core-bundle[4.4.0, ..., 4.13.28] but these were not loaded, likely because it conflicts with another require.
    - terminal42/notification_center[1.7.0, ..., 1.7.2] require contao/core-bundle ^4.13 -> found contao/core-bundle[4.13.0, ..., 4.13.28] but these were not loaded, likely because it conflicts with another require.
    - con4gis/pwa is locked to version v2.5.7 and an update of this package was not requested.
    - inspiredminds/contao-event-registration 1.2.2 requires terminal42/notification_center ^1.5 -> satisfiable by terminal42/notification_center[1.5.0, ..., 1.7.2].
    - terminal42/notification_center[1.5.0, ..., 1.6.4] require contao/core-bundle ~3.2 || ~4.1 -> satisfiable by contao/core[3.2.0, ..., 3.5.40].
    - Root composer.json requires inspiredminds/contao-event-registration ^1.2 -> satisfiable by inspiredminds/contao-event-registration[1.2.0, 1.2.1, 1.2.2].
[105.0MiB/10.12s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[40.7MiB/10.16s] Memory usage: 40.7MB (peak: 199.68MB), time: 10.16s.
[40.7MiB/10.16s] Finished Composer Cloud resolving.
# Cloud Job ID HPERjYCbj9zLzrip0nDDUCC3Ps71KiBnlSoVI5GBEpBY11BheONj3kRmDYNSHzwTXWuvUXPPBqagtGRLdtoECzep8Q5qDzAjMqAbQRpkzZ failed
vendor/bin/contao-console contao:maintenance-mode enable
composer install --dry-run

**Comment by fritzmg** [comment]
Yes, version 1.2.2 is unlocked for Contao 5, see https://packagist.org/packages/inspiredminds/contao-event-registration#1.2.2
However, `terminal42/notification_center` has no release for Contao 5 yet: https://packagist.org/packages/terminal42/notification_center
