### ISSUE TITLE
Keine Sicherheitsabfrage beim Löschen von Registrierungen

### ISSUE THREAD

**Issue by dive13** [inspiredminds/contao-event-registration#19]
Hi,
beim Löschen von Einträgen in der Registrierungsliste (beim jeweiligen Event) kommt keine Sicherheitsabfrage, wie sonst bei Contao üblich. Der Eintrag wird sofort gelöscht. Wäre gut, wenn sich das auch entspr. dem Contao-Standard verhält.

Contao 4.13.30
Event Registration 1.2.1

**Comment by fritzmg** [comment]
Added in `1.2.3` :)

**Comment by dive13** [comment]
wow, so schnell! Danke sehr ;-)
