### ISSUE TITLE
Show the custom amount in the list

### ISSUE THREAD

**Issue by sebssch** [inspiredminds/contao-event-registration#2]
if there is a custom amount field configured in the form it would be nice if the list of registration show the individual amount of each registration. 
<img width="599" alt="Events | bv-roding sgt 2021-05-27 22-23-31" src="https://user-images.githubusercontent.com/18069290/119894278-b5902d80-bf3c-11eb-94f4-dffb17af5924.png">

**Comment by fritzmg** [comment]
Have you tried the following yet?

```php
// contao/dca/tl_event_registration.php
$GLOBALS['TL_DCA']['tl_event_registration']['list']['label']['fields'] = ['amount', 'firstname', 'lastname', 'email'];
$GLOBALS['TL_DCA']['tl_event_registration']['list']['label']['format'] = '<b>[%s]</b> %s %s, %s';
```

**Comment by sebssch** [comment]
It doesn't work.

**Comment by fritzmg** [comment]
I tested it locally and the example works fine. May be you did not rebuild your application cache after making these changes? 

Anyway, I am closing this as this is easy to customize and described.

**Comment by sebssch** [comment]
In my form the last name was `name` not `lastname`. Sorry, it was my fault. Thank you for helping.
