### ISSUE TITLE
Details der Anmeldungen werden nicht mehr geladen

### ISSUE THREAD

**Issue by BlackThunder22** [inspiredminds/contao-event-registration#20]
Hallo zusammen,

ich kann mir neuerdings über das Info-Zeichen nicht mehr die Details der Anmeldungen anzeigen lassen.
Hatte erst die Vermutung dass die Erweiterung [contao-fieldset-duplication](https://github.com/inspiredminds/contao-fieldset-duplication) die Datenbank verändert hat, aber nach der Deinstallation funktioniert es immer noch nicht.

![2023-10-30 21_25_25-Events Ausfahrten Winter 2022_2023](https://github.com/inspiredminds/contao-event-registration/assets/114856692/7affb81b-42de-440b-8ee9-0654d66adb48)

`An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'pid' in where clause is ambiguous`

`Column 'pid' in where clause is ambiguous" at /mnt/web524/b3/85/51404385/htdocs/contao/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 72 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NonUniqueFieldNameException(code: 1052): An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'pid' in where clause is ambiguous at /mnt/web524/b3/85/51404385/htdocs/contao/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:72)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1052): SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'pid' in where clause is ambiguous at /mnt/web524/b3/85/51404385/htdocs/contao/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'pid' in where clause is ambiguous at /mnt/web524/b3/85/51404385/htdocs/contao/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130)"} []`

Die PID in der Datenbank ist mehrfach vorhanden, die ID hingegen jedoch eindeutig.

Was könnte hier passiert sein?

**Comment by fritzmg** [comment]
Please use the debug mode and post the stack trace.

**Comment by BlackThunder22** [comment]
<html>
<body>


[3/3] NonUniqueFieldNameException
--
Doctrine\DBAL\Exception\NonUniqueFieldNameException: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'pid' in where clause is ambiguous    at vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:72   at Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert()      (vendor/doctrine/dbal/src/Connection.php:1938)   at Doctrine\DBAL\Connection->handleDriverException()      (vendor/doctrine/dbal/src/Connection.php:1880)   at Doctrine\DBAL\Connection->convertExceptionDuringQuery()      (vendor/doctrine/dbal/src/Connection.php:1105)   at Doctrine\DBAL\Connection->executeQuery()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:279)   at Contao\Database\Statement->query()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:235)   at Contao\Database\Statement->execute()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:1096)   at Contao\Model::find()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:962)   at Contao\Model::findBy()      (vendor/inspiredminds/contao-event-registration/src/EventListener/DataContainer/EventRegistration/ConfigOnShowCallbackListener.php:44)   at InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ConfigOnShowCallbackListener->__invoke()      (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:517)   at Contao\DC_Table->show()      (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:667)   at Contao\Backend->getBackendModule()      (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:168)   at Contao\BackendMain->run()      (vendor/contao/core-bundle/src/Controller/BackendController.php:49)   at Contao\CoreBundle\Controller\BackendController->mainAction()      (vendor/symfony/http-kernel/HttpKernel.php:163)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw()      (vendor/symfony/http-kernel/HttpKernel.php:75)   at Symfony\Component\HttpKernel\HttpKernel->handle()      (vendor/symfony/http-kernel/Kernel.php:202)   at Symfony\Component\HttpKernel\Kernel->handle()      (web/index.php:44)


</body>
</html>

<html>
<body>


[2/3] Exception
--
Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'pid' in where clause is ambiguous    at vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28   at Doctrine\DBAL\Driver\PDO\Exception::new()      (vendor/doctrine/dbal/src/Driver/PDO/Statement.php:132)   at Doctrine\DBAL\Driver\PDO\Statement->execute()      (vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php:69)   at Doctrine\DBAL\Driver\Middleware\AbstractStatementMiddleware->execute()      (vendor/doctrine/dbal/src/Logging/Statement.php:98)   at Doctrine\DBAL\Logging\Statement->execute()      (vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php:69)   at Doctrine\DBAL\Driver\Middleware\AbstractStatementMiddleware->execute()      (vendor/symfony/doctrine-bridge/Middleware/Debug/Statement.php:72)   at Symfony\Bridge\Doctrine\Middleware\Debug\Statement->execute()      (vendor/doctrine/dbal/src/Connection.php:1098)   at Doctrine\DBAL\Connection->executeQuery()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:279)   at Contao\Database\Statement->query()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:235)   at Contao\Database\Statement->execute()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:1096)   at Contao\Model::find()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:962)   at Contao\Model::findBy()      (vendor/inspiredminds/contao-event-registration/src/EventListener/DataContainer/EventRegistration/ConfigOnShowCallbackListener.php:44)   at InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ConfigOnShowCallbackListener->__invoke()      (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:517)   at Contao\DC_Table->show()      (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:667)   at Contao\Backend->getBackendModule()      (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:168)   at Contao\BackendMain->run()      (vendor/contao/core-bundle/src/Controller/BackendController.php:49)   at Contao\CoreBundle\Controller\BackendController->mainAction()      (vendor/symfony/http-kernel/HttpKernel.php:163)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw()      (vendor/symfony/http-kernel/HttpKernel.php:75)   at Symfony\Component\HttpKernel\HttpKernel->handle()      (vendor/symfony/http-kernel/Kernel.php:202)   at Symfony\Component\HttpKernel\Kernel->handle()      (web/index.php:44)


</body>
</html>

<html>
<body>
<div class="container" style="max-width: 1024px; margin: 0px auto; padding: 0px 15px; color: rgb(34, 34, 34); font-family: Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="sf-tabs" data-processed="true"><div class="block" id="tab-0-2" style="display: block;"><div class="tab-content">

[1/3] PDOException
--
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'pid' in where clause is ambiguous    at vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130   at PDOStatement->execute()      (vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130)   at Doctrine\DBAL\Driver\PDO\Statement->execute()      (vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php:69)   at Doctrine\DBAL\Driver\Middleware\AbstractStatementMiddleware->execute()      (vendor/doctrine/dbal/src/Logging/Statement.php:98)   at Doctrine\DBAL\Logging\Statement->execute()      (vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php:69)   at Doctrine\DBAL\Driver\Middleware\AbstractStatementMiddleware->execute()      (vendor/symfony/doctrine-bridge/Middleware/Debug/Statement.php:72)   at Symfony\Bridge\Doctrine\Middleware\Debug\Statement->execute()      (vendor/doctrine/dbal/src/Connection.php:1098)   at Doctrine\DBAL\Connection->executeQuery()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:279)   at Contao\Database\Statement->query()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:235)   at Contao\Database\Statement->execute()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:1096)   at Contao\Model::find()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:962)   at Contao\Model::findBy()      (vendor/inspiredminds/contao-event-registration/src/EventListener/DataContainer/EventRegistration/ConfigOnShowCallbackListener.php:44)   at InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ConfigOnShowCallbackListener->__invoke()      (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:517)   at Contao\DC_Table->show()      (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:667)   at Contao\Backend->getBackendModule()      (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:168)   at Contao\BackendMain->run()      (vendor/contao/core-bundle/src/Controller/BackendController.php:49)   at Contao\CoreBundle\Controller\BackendController->mainAction()      (vendor/symfony/http-kernel/HttpKernel.php:163)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw()      (vendor/symfony/http-kernel/HttpKernel.php:75)   at Symfony\Component\HttpKernel\HttpKernel->handle()      (vendor/symfony/http-kernel/Kernel.php:202)   at Symfony\Component\HttpKernel\Kernel->handle()      (web/index.php:44)

</div></div></div></div><div id="sfwdtc5fb5d" class="sf-toolbar" role="region" aria-label="Symfony Web Debug Toolbar" data-sfurl="https://www.sbh-haigerloch.de/_wdt/c5fb5d" style="color: rgb(34, 34, 34); font-family: Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: block;"><br class="Apple-interchange-newline">
</body>
</html>

**Comment by fritzmg** [comment]
Can you please install `dev-main` and check if the error still occurs then?

**Comment by BlackThunder22** [comment]
> Can you please install `dev-main` and check if the error still occurs then?

Unfortunately it doesn't work yet

```
[3/3] InvalidFieldNameException
Doctrine\DBAL\Exception\InvalidFieldNameException:
An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tl_form.pid' in 'where clause'

  at vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:67
  at Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert()
     (vendor/doctrine/dbal/src/Connection.php:1938)
  at Doctrine\DBAL\Connection->handleDriverException()
     (vendor/doctrine/dbal/src/Connection.php:1880)
  at Doctrine\DBAL\Connection->convertExceptionDuringQuery()
     (vendor/doctrine/dbal/src/Connection.php:1105)
  at Doctrine\DBAL\Connection->executeQuery()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:279)
  at Contao\Database\Statement->query()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:235)
  at Contao\Database\Statement->execute()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:1096)
  at Contao\Model::find()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:962)
  at Contao\Model::findBy()
     (vendor/inspiredminds/contao-event-registration/src/EventListener/DataContainer/EventRegistration/ConfigOnShowCallbackListener.php:45)
  at InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ConfigOnShowCallbackListener->__invoke()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:517)
  at Contao\DC_Table->show()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:667)
  at Contao\Backend->getBackendModule()
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:168)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:49)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:163)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:75)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web/index.php:44)                
[2/3] Exception
Doctrine\DBAL\Driver\PDO\Exception:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tl_form.pid' in 'where clause'

  at vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28
  at Doctrine\DBAL\Driver\PDO\Exception::new()
     (vendor/doctrine/dbal/src/Driver/PDO/Statement.php:132)
  at Doctrine\DBAL\Driver\PDO\Statement->execute()
     (vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php:69)
  at Doctrine\DBAL\Driver\Middleware\AbstractStatementMiddleware->execute()
     (vendor/doctrine/dbal/src/Logging/Statement.php:98)
  at Doctrine\DBAL\Logging\Statement->execute()
     (vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php:69)
  at Doctrine\DBAL\Driver\Middleware\AbstractStatementMiddleware->execute()
     (vendor/symfony/doctrine-bridge/Middleware/Debug/DBAL3/Statement.php:78)
  at Symfony\Bridge\Doctrine\Middleware\Debug\DBAL3\Statement->execute()
     (vendor/doctrine/dbal/src/Connection.php:1098)
  at Doctrine\DBAL\Connection->executeQuery()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:279)
  at Contao\Database\Statement->query()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:235)
  at Contao\Database\Statement->execute()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:1096)
  at Contao\Model::find()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:962)
  at Contao\Model::findBy()
     (vendor/inspiredminds/contao-event-registration/src/EventListener/DataContainer/EventRegistration/ConfigOnShowCallbackListener.php:45)
  at InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ConfigOnShowCallbackListener->__invoke()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:517)
  at Contao\DC_Table->show()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:667)
  at Contao\Backend->getBackendModule()
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:168)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:49)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:163)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:75)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web/index.php:44)                
[1/3] PDOException
PDOException:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tl_form.pid' in 'where clause'

  at vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130
  at PDOStatement->execute()
     (vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130)
  at Doctrine\DBAL\Driver\PDO\Statement->execute()
     (vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php:69)
  at Doctrine\DBAL\Driver\Middleware\AbstractStatementMiddleware->execute()
     (vendor/doctrine/dbal/src/Logging/Statement.php:98)
  at Doctrine\DBAL\Logging\Statement->execute()
     (vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php:69)
  at Doctrine\DBAL\Driver\Middleware\AbstractStatementMiddleware->execute()
     (vendor/symfony/doctrine-bridge/Middleware/Debug/DBAL3/Statement.php:78)
  at Symfony\Bridge\Doctrine\Middleware\Debug\DBAL3\Statement->execute()
     (vendor/doctrine/dbal/src/Connection.php:1098)
  at Doctrine\DBAL\Connection->executeQuery()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:279)
  at Contao\Database\Statement->query()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:235)
  at Contao\Database\Statement->execute()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:1096)
  at Contao\Model::find()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:962)
  at Contao\Model::findBy()
     (vendor/inspiredminds/contao-event-registration/src/EventListener/DataContainer/EventRegistration/ConfigOnShowCallbackListener.php:45)
  at InspiredMinds\ContaoEventRegistration\EventListener\DataContainer\EventRegistration\ConfigOnShowCallbackListener->__invoke()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:517)
  at Contao\DC_Table->show()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:667)
  at Contao\Backend->getBackendModule()
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:168)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:49)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:163)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:75)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web/index.php:44)   
```             

Database:

![Uploading 2023-10-31 21_12_50-tl_event_registration _ STRATO phpMyAdmin 4.9.2.png…]()

**Comment by fritzmg** [comment]
Ah, my mistake. Please try again with the updated `dev-main` branch.

**Comment by BlackThunder22** [comment]
> Ah, my mistake. Please try again with the updated `dev-main` branch.

great, works again now.
Thank you!
