### ISSUE TITLE
Details of a registration shows "array" instead of selected values

### ISSUE THREAD

**Issue by arboc** [inspiredminds/contao-event-registration#22]
Example:   
We have an registration form, where the participant can choose from some options, if he needs attandance:  
![image](https://github.com/inspiredminds/contao-event-registration/assets/4447843/00553e8c-422f-4170-8a54-705d3a1501c9)

When the details of that registration is shown, the choosen values for this form field are not shown. Instead there ist a text "array":
![image](https://github.com/inspiredminds/contao-event-registration/assets/4447843/0a5e08c3-2c93-4c26-9262-4e9f98ba01a2)

This occurs, when you can select multiple values (like Checkbox-Menu).

**Comment by fritzmg** [comment]
Yes, fields with multiple values are not supported currently. But it should be straightforward to implode them to comma separated values I guess. Can you provide a PR?

**Comment by arboc** [comment]
not at this moment.... next week I will do.

**Comment by arboc** [comment]
I'va had a short look at the sources.

I will suggest not to convert into a comma separated list.   
Instead every value should be shown in a separate line.

@fritzmg What do you thnk?
