### ISSUE TITLE
"eventtitle" not working anymore

### ISSUE THREAD

**Issue by SpeGal** [inspiredminds/contao-event-registration#28]
When this tool was integrated in calendar-extended-bundle there used to be a function that allowed to insert the "eventtitle" in a hidden form field. In the never versions of this event registration this function is not working anymore. There seems to be a shift in the logic that for every event you would have to create your own form. Where the reality is usually so that multiple events would use the same form.

Or maybe in the documentation the information is just missing about how to save the event title in leads along with the rest of the form?

**Comment by fritzmg** [comment]
I am not quite sure what you are trying to do. Every registration is attached to a specific event, so sending the event title with the registration form is superfluous.

If you need the even title in the notification of your registration form, then you can use the respective simple token for that.

> Or maybe in the documentation the information is just missing about how to save the event title in leads along with the rest of the form?

See here: https://github.com/inspiredminds/contao-event-registration?tab=readme-ov-file#simple-tokens

**Comment by SpeGal** [comment]
Not if you want to safe it in leads (how it used to be). Imagine an event website with hundreds of events. The booking departement needs to export the registrations. They used to have one list with all information (including the event title). Now they would have to navigate to each of the hundreds of events to export hundreds of single lists that are most likely not even usuable for them, because of the way they are formated. 

The tool is great and the logic to store the registration information directly in the event might be plausible in some cases with few events. But in a bigger scale this leads to big issues. To make the extension usable for a big number of events, the known feature of transmitting the event title is crucial. 

For the confirmations message, email and so on there is the solution of ##event_*## (##event_title##) already implemented. That is great, but it doesnt work for the hidden form field because the form has not been sent yet. So a solution similar to the previous "eventtitle" would be mostly welcome.

**Comment by fritzmg** [comment]
> Not if you want to safe it in leads (how it used to be).

What do you mean by that? This extension does not use Leads.

**Comment by SpeGal** [comment]
But in combination with leads and notification center it is a very powerful tool. 

This post is about the lost link between leads and event-registration due to the loss of "eventtitle". If this could be implemented again, these extensions could work in symbiosis again and help projects with a big amount of events to handle the registration process.

**Comment by fritzmg** [comment]
> If this could be implemented again

What do you mean by again? Such a feature never existed.

If you need to store the event title in leads then you will need to implement that in your own custom solution. This extension has nothing to do with that.

**Comment by SpeGal** [comment]
When the event-registration was still part of calendar-extended-bundle it had the feature to transmit the "eventtitle", "startdate", "enddate" and "count" (now "amount") in hidden form fields. That is what I am refferring to. I thought it had been forgotten to be programmed in the process of seperating the two extensions since I saw this as a cruicial part of the registration process. From the four only "count" survived as "amount".

I understand now, that the developer has changed and you probably don't know about all the functionalities in the past.

Could we change this from a bug to a feature request then?

Here my thinking again about why this would be an important feature:
- the export options of event-registration are fairly limited, leads comes with a lot of options to configure the export therefore it would be ideal to be able to store the registration data in leads
- leads therefore needs the eventtitle, startdate, enddate (just in the same way you implemented "amount" or renamed "count")

Thank you very much for all your effort to enrich the Contao Community with code and extensions to make things work well. You are a very important member of the Contao project and I appreciate your work highly!

**Comment by fritzmg** [comment]
> When the event-registration was still part of calendar-extended-bundle

You are confusing something here. This is the `inspiredminds/contao-event-registration` extension, not `kmielke/calendar-extended-bundle`. The `inspiredminds/contao-event-registration` extension has absolutely nothing to do with the `kmielke/calendar-extended-bundle` extension, nor was it ever part of it.
