### ISSUE TITLE
An error occurred when submitting a registration form

### ISSUE THREAD

**Issue by BlackThunder22** [inspiredminds/contao-event-registration#32]
[2024-10-07T15:16:06.083669+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'waiting' at row 1" at /mnt/webXXX/htdocs/contao/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 118 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 1366): An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'waiting' at row 1 at /mnt/webXXX/htdocs/contao/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:118)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1366): SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'waiting' at row 1 at /mnt/webXXX/htdocs/contao/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'waiting' at row 1 at /mnt/webXXX/htdocs/contao/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130)"} [

Contao Version 4.13.32
Plugin Version 1.3.7

[
![2024-10-07 16_21_52-Es ist ein Fehler aufgetreten](https://github.com/user-attachments/assets/5f132b2b-7bc2-4b11-978d-bc5a792709fd)
](url)

**Comment by fritzmg** [comment]
Please do not post just single exceptions. You'll need to post exact reproduction steps, use the debug mode and post the stack trace.

**Comment by BlackThunder22** [comment]
`<html>
<body>

[3/3] DriverException
--
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'waiting' at row 1    at vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:118   at Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert()      (vendor/doctrine/dbal/src/Connection.php:1939)   at Doctrine\DBAL\Connection->handleDriverException()      (vendor/doctrine/dbal/src/Connection.php:1881)   at Doctrine\DBAL\Connection->convertExceptionDuringQuery()      (vendor/doctrine/dbal/src/Connection.php:1106)   at Doctrine\DBAL\Connection->executeQuery()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:279)   at Contao\Database\Statement->query()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:235)   at Contao\Database\Statement->execute()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:498)   at Contao\Model->save()      (vendor/inspiredminds/contao-event-registration/src/EventListener/EventRegistrationFormListener.php:75)   at InspiredMinds\ContaoEventRegistration\EventListener\EventRegistrationFormListener->__invoke()      (vendor/contao/core-bundle/src/Resources/contao/forms/Form.php:573)   at Contao\Form->processFormData()      (vendor/contao/core-bundle/src/Resources/contao/forms/Form.php:258)   at Contao\Form->compile()      (vendor/contao/core-bundle/src/Resources/contao/classes/Hybrid.php:230)   at Contao\Hybrid->generate()      (vendor/contao/core-bundle/src/Resources/contao/forms/Form.php:90)   at Contao\Form->generate()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:691)   at Contao\Controller::getForm()      (vendor/inspiredminds/contao-event-registration/src/EventRegistration.php:134)   at InspiredMinds\ContaoEventRegistration\EventRegistration->getRegistrationForm()      (vendor/inspiredminds/contao-event-registration/src/EventRegistration.php:53)   at InspiredMinds\ContaoEventRegistration\EventRegistration->InspiredMinds\ContaoEventRegistration\{closure}()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Template.php:151)   at Contao\Template->__get()      (vendor/inspiredminds/contao-event-registration/contao/templates/mod_event_registration_form.html5:11)   at include('/mnt/web524/b3/85/51404385/htdocs/contao/vendor/inspiredminds/contao-event-registration/contao/templates/mod_event_registration_form.html5')      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php:108)   at Contao\Template->inherit()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Template.php:295)   at Contao\Template->parse()      (vendor/contao/core-bundle/src/Resources/contao/classes/FrontendTemplate.php:43)   at Contao\FrontendTemplate->parse()      (vendor/contao/core-bundle/src/Resources/contao/classes/FragmentTemplate.php:36)   at Contao\FragmentTemplate->compile()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Template.php:322)   at Contao\Template->getResponse()      (vendor/contao/core-bundle/src/Resources/contao/classes/FrontendTemplate.php:85)   at Contao\FrontendTemplate->getResponse()      (vendor/contao/core-bundle/src/Resources/contao/classes/FragmentTemplate.php:25)   at Contao\FragmentTemplate->getResponse()      (vendor/inspiredminds/contao-event-registration/src/Controller/FrontendModule/EventRegistrationFormController.php:44)   at InspiredMinds\ContaoEventRegistration\Controller\FrontendModule\EventRegistrationFormController->getResponse()      (vendor/contao/core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php:40)   at Contao\CoreBundle\Controller\FrontendModule\AbstractFrontendModuleController->__invoke()      (vendor/symfony/http-kernel/HttpKernel.php:163)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw()      (vendor/symfony/http-kernel/HttpKernel.php:75)   at Symfony\Component\HttpKernel\HttpKernel->handle()      (vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php:86)   at Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle()      (vendor/symfony/http-kernel/Fragment/InlineFragmentRenderer.php:80)   at Symfony\Component\HttpKernel\Fragment\InlineFragmentRenderer->render()      (vendor/symfony/http-kernel/Fragment/FragmentHandler.php:85)   at Symfony\Component\HttpKernel\Fragment\FragmentHandler->render()      (vendor/contao/core-bundle/src/Fragment/FragmentHandler.php:69)   at Contao\CoreBundle\Fragment\FragmentHandler->render()      (vendor/contao/core-bundle/src/Resources/contao/modules/ModuleProxy.php:60)   at Contao\ModuleProxy->generate()      (vendor/contao/core-bundle/src/Resources/contao/elements/ContentModule.php:59)   at Contao\ContentModule->generate()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:622)   at Contao\Controller::getContentElement()      (vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticle.php:197)   at Contao\ModuleArticle->compile()      (vendor/contao/core-bundle/src/Resources/contao/modules/Module.php:214)   at Contao\Module->generate()      (vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticle.php:70)   at Contao\ModuleArticle->generate()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:550)   at Contao\Controller::getArticle()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:392)   at Contao\Controller::getFrontendModule()      (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:190)   at Contao\PageRegular->prepare()      (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:60)   at Contao\PageRegular->getResponse()      (vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:320)   at Contao\FrontendIndex->renderPage()      (vendor/symfony/http-kernel/HttpKernel.php:163)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw()      (vendor/symfony/http-kernel/HttpKernel.php:75)   at Symfony\Component\HttpKernel\HttpKernel->handle()      (vendor/symfony/http-kernel/Kernel.php:202)   at Symfony\Component\HttpKernel\Kernel->handle()      (web/index.php:44)


</body>
</html>`

**Comment by fritzmg** [comment]
Again, you have posted this without any comments. Also please don't just copy and paste the HTML version of the stack trace. Click on the "Stack Trace" tab first and copy the stack trace from there. If there are multiple ones: use the first one (the one at the very bottom).

**Comment by BlackThunder22** [comment]
[FireShot Capture 020 - An exception occurred while executing a query.pdf](https://github.com/user-attachments/files/17284224/FireShot.Capture.020.-.An.exception.occurred.while.executing.a.query.pdf)

Sorry, I edited the post again. Is it OK now? I don't quite understand how else I should copy it

**Comment by BlackThunder22** [comment]
Is version 2.x.x only for contao 5 and version 1.3x for contao 4?

**Comment by BlackThunder22** [comment]
Is the information provided sufficient for an error analysis? Is this problem caused by the added waiting list function?
If there is a temporary workaround, I would be grateful.
I will soon have to put the events for the coming winter season online for our ski club.

**Comment by fritzmg** [comment]
I am not sure why this error occurs in the first place. There should not be an empty string in the `waiting` variable of the model. It should always be boolean: 

https://github.com/inspiredminds/contao-event-registration/blob/3ef26657a027430f20f43a39db33777985998fbf/src/EventListener/EventRegistrationFormListener.php#L60

**Comment by BlackThunder22** [comment]
> I am not sure why this error occurs in the first place. There should not be an empty string in the `waiting` variable of the model. It should always be boolean:
> 
> https://github.com/inspiredminds/contao-event-registration/blob/3ef26657a027430f20f43a39db33777985998fbf/src/EventListener/EventRegistrationFormListener.php#L60

I can provide access to the system if that helps troubleshooting, just let me know.

**Comment by BlackThunder22** [comment]
Is there anything else I can add to help troubleshoot the problem?
I had a friend check the code, but he also found it difficult to determine the cause.

**Comment by BlackThunder22** [comment]
Just dug into it and noticed that the order in which contao writes the values into the db does not match the actual order of the fields in the db.

If I just modify the sql statement from the debug output and swap _form_data_ with _waiting_, I can insert the record via phpmyadmin without any issues.

Not sure whether this only affects my installation or also others'. (Hadn't had any errors on contao updates in the past though)

![database_event-registration](https://github.com/user-attachments/assets/da5a6859-9d61-4054-9371-df1716f3a890)

![insert_statement_event-registration](https://github.com/user-attachments/assets/17229e7d-9501-48eb-b8bc-9c292207fcbb)


I'm not an expert regarding contao. For testing, I tried to manually edit the dca file and to swap the fields there:

https://github.com/inspiredminds/contao-event-registration/blob/ba34b57684cc49d8468de116acb6d1075e6210c5/contao/dca/tl_event_registration.php#L78-L87

After cleaning all caches and running composer install, the problem was not resolved however.

Is this even the right place to swap the field's order?
Could you please tell me what I have to do in order to reload the vendor files to verify that this fixes the issue?

**Comment by fritzmg** [comment]
I am not sure what the order has anything to do with this? The issue is that in your case a string value is asked to be saved to the `waiting` field, even though it should always be a boolean (or integer).

**Comment by johnmoarr** [comment]
Think the issue is that it tries to write the content that should go into `form_data` into the `waiting` field and vice versa (as also can be seen on the screenshot of the insert statement that was logged when trying to add an event registration). The actual value for $waiting seems fine.

**Comment by fritzmg** [comment]
No, in your screenshot the value to be written for the `waiting` field is `false`. However, that provides a clue.

What are the exact versions of

* PHP
* Contao
* This extension

you are currently running?

**Comment by BlackThunder22** [comment]
> No, in the screenshot the value to be written for the `waiting` field is `false`. However, that provides a clue.
> 
> What are the exact versions of
> 
> * PHP
> * Contao
> * This extension
> 
> you are currently running?

* PHP 8.3.12
* Contao 4.13.32
* Extension Version 1.3.7

**Comment by johnmoarr** [comment]
Ok, wasn't sure whether the order doesn't matter if the column names are provided explicitly. The w3c doc was a bit misleading there. Just also noticed, that all other boolean values are represented as 0 and 1 in the insert statement, except for the waiting flag.

**Comment by fritzmg** [comment]
> Contao 4.13.32

The newest version is 4.13.39 - you should always update first before tackling problems.

* There are several security issues in Contao and Symfony in the version you are using.
* There have been bug fixes regarding boolean values in Contao Models when using PDO under PHP 8.

**Comment by BlackThunder22** [comment]
> > Contao 4.13.32
> 
> The newest version is 4.13.49 - you should always update all packages first before tackling problems.
> 
> * There are several security issues in Contao and Symfony in the version you are using.
> * There have been bug fixes regarding boolean values in Contao Models (or rather Contao's legacy database abstraction) when using PDO under PHP 8 (see [Automatically set `ParameterType::BOOLEAN` for booleans contao/contao#7126](https://github.com/contao/contao/pull/7126)).

that really solved the problem.

Sorry, I wouldn't have thought of that because the updater didn't show me the new version. I had to change the version number manually.

Thank you very much!

**Comment by fritzmg** [comment]
> Sorry, I wouldn't have thought of that because the updater didn't show me the new version. I had to change the version number manually.

You should always set it to `4.13.*` and run full package updates regularly, especially when encountering an issue. If you use services like https://www.trakked.io/ they will notify you of any critical security updates automatically (and can also automatically install them for you).
