### ISSUE TITLE
Contao 4.13.2: Templatevariablen & Registrierungsbestätigung funktionieren nicht

### ISSUE THREAD

**Issue by jankout** [inspiredminds/contao-event-registration#7]
Hallo, 

ich habe alles nach dieser Anleitung im [Contaoforum](https://community.contao.org/de/showthread.php?82553-Einrichtung-inspiredminds-contao-event-registration&highlight=event-registration) und euerer Beschreibung umgesetzt. 

Dabei habe ich eine Bestätigungsseite erstellt, wo auch das entsprechende Modul eingebunden ist. Im Modul selbst habe ich auch die Node und die zugehörige Benachrichtigung eingebunden. Im Eventkalender habe ich die Weiterleitungen auch korrekt bestimmt.

Als ich folgende Logik aus eurem Template übernommen und in `event_full.html5` eingetragen habe, kam die Meldung, dass man sich nicht mehr registrieren kann, obwohl das nicht stimmt. Erst als ich das Module mit dem Formular auf der gleichen Eventleserseite eingebunden habe, konnte das Fornular wie erwartet gezeigt werden - die Meldung aus dem Event-full-Template zeigt aber weiterhin, dass man sich nicht mehr anmelden kann. Daher musste ich es löschen.

```
<?php if (!$this->canRegister): ?>
  <div class="registration-form" id="registration">
    <p class="cannot-register"><?= $this->trans('cannot_register', [], 'im_contao_event_registration') ?></p>
    <?php else: ?>
    <h2>Registrierung</h2>
    <?= $this->registrationForm ?>
  </div>
    <?php endif; ?>
```

Im Registrierungsformular habe ich eine normale E-Mailbenachrichtigung verkünpft. Diese verschickt eine E-Mail korrekt. Die Benachrichtigung für die Bestätigung wird aber nicht verschickt. 

![contao_registrierungserweitrung_3](https://user-images.githubusercontent.com/3715050/161507256-52a5eaac-8a09-4609-92fe-0b930c7cf44d.png)

Woran mag es noch liegen, dass es noch nicht funktioniert, wie es funktionieren soll?

**Comment by fritzmg** [comment]
@jankout are you also using `kmielke/calendar-extended-bundle`?

**Comment by jankout** [comment]
yes, now I'm using the other extension. :-)

**Comment by fritzmg** [comment]
No, I meant - when you ran into these issues, did you have `kmielke/calendar-extended-bundle` already installed? See https://github.com/inspiredminds/contao-event-registration/issues/8

**Comment by fritzmg** [comment]
Closing due to lack of feedback.

**Comment by dive13** [comment]
Ich möchte das hier nochmal aufgreifen. Die Registrierungs-Bestätigung funktioniert nicht unter 4.13.10. Andere Mails via Notification Center gehen problemlos durch.

Und nein, ich habe `kmielke/calendar-extended-bundle` dzt. nicht mehr installiert (hatte es zwar kurzfristig, aber wegen anderer Probleme mit der extension wieder deinstalliert).
