### ISSUE TITLE
Fehlermeldung bei Aufruf der Registrierungen im Backen

### ISSUE THREAD

**Issue by contaoacademy** [inspiredminds/contao-event-registration#9]
Contao 4.9.30
Version 1.2.0

Wenn ich im Backend die Registrierungen anzeigen lassen möchte, dann kommt folgende Fehlermeldung.

`[2022-06-28 09:44:08] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of InspiredMinds\ContaoEventRegistration\EventRegistration\LabelBuilder::__invoke() must be of the type string or null, bool returned" at /www/htdocs/XXX/XXX/vendor/inspiredminds/contao-event-registration/src/EventRegistration/LabelBuilder.php line 72 {"exception":"[object] (TypeError(code: 0): Return value of InspiredMinds\\ContaoEventRegistration\\EventRegistration\\LabelBuilder::__invoke() must be of the type string or null, bool returned at /www/htdocs/XXX/XXX/vendor/inspiredminds/contao-event-registration/src/EventRegistration/LabelBuilder.php:72)"} []`

Als Übergangslösung habe ich aktuell ein Downgrade auf Version 1.1.4 gemacht.

**Comment by fritzmg** [comment]
As a workaround you can also update to PHP 8 - there the error won't occur ;)

**Comment by fritzmg** [comment]
Can you please test again with `dev-main`?

**Comment by contaoacademy** [comment]
> Can you please test again with `dev-main`?

Works, no error any more.
